### ISSUE TITLE
Compiler etc.

### ISSUE THREAD

**Issue by DoctorWkt** [Johnlon/spam-1#1]
John, just saw your reply on my CSCv2 repo. Maybe e-mail is a better way to communicate? whiskey kilo tango at tuhs dot org. A compiler for even a subset of C is hard. I've written one for a really tiny language, see [https://github.com/DoctorWkt/CSCv2/blob/master/Compiler.md](https://github.com/DoctorWkt/CSCv2/blob/master/Compiler.md). The compiler is in Perl; I see you're mainly Java/Groovy, so it shouldn't be too hard to translate across. Is there a list of instructions for spam-1? Anyway, e-mail me back. Cheers, Warren

**Comment by Johnlon** [comment]
Months later I am still working on the design and sim :(
Will defo be looking at your toolchain again.
Thanks John
